#!/usr/bin/env bash

## Description: Fetches a DB dump
## Usage: fetch-db
## Example: ddev fetch-db

mysqldump \
  --host="${REMOTE_HOST}" \
  --user="${REMOTE_DB_USER}" \
  --password="${REMOTE_DB_PASSWORD}" \
  --single-transaction \
  --no-tablespaces \
  "${REMOTE_DB}" > ".dbdumps/${REMOTE_DB}_$(date +"%Y-%m-%dT%Y-%H%M").sql"
