name: swissartg
type: drupal
docroot: web
php_version: "8.3"
webserver_type: apache-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
    type: mysql
    version: "8.0"
use_dns_when_possible: true
timezone: Europe/Zurich
composer_version: "2"
web_environment: []
corepack_enable: true
webimage_extra_packages:
  - rclone
